import { Caregiver, ChatMessage, DailyCareLog, Interview } from "@/types";

export const MOCK_CAREGIVERS: Caregiver[] = [
  {
    id: "cg-1",
    nome: "Patricia Lima",
    idade: 42,
    foto: "https://picsum.photos/seed/caregiver1/600/400",
    cidade: "Sao Paulo",
    bairro: "Vila Mariana",
    valorHora: 38,
    experienciaAnos: 9,
    avaliacao: 4.9,
    distanciaKm: 3.2,
    verificado: true,
    disponivel: ["Manha", "Tarde"],
    especialidades: ["companhia", "medicacao", "mobilidade"],
    descricao:
      "Cuidadora com experiencia em rotina medicamentosa e acompanhamento para consultas.",
  },
  {
    id: "cg-2",
    nome: "Marcos Teixeira",
    idade: 34,
    foto: "https://picsum.photos/seed/caregiver2/600/400",
    cidade: "Sao Paulo",
    bairro: "Saude",
    valorHora: 32,
    experienciaAnos: 6,
    avaliacao: 4.7,
    distanciaKm: 4.6,
    verificado: true,
    disponivel: ["Noite", "Plantao"],
    especialidades: ["noturno", "higiene", "mobilidade"],
    descricao:
      "Atua em plantoes noturnos e suporte para banho, troca e mobilidade segura.",
  },
  {
    id: "cg-3",
    nome: "Eliane Sousa",
    idade: 47,
    foto: "https://picsum.photos/seed/caregiver3/600/400",
    cidade: "Sao Paulo",
    bairro: "Ipiranga",
    valorHora: 45,
    experienciaAnos: 12,
    avaliacao: 5,
    distanciaKm: 6.1,
    verificado: true,
    disponivel: ["Manha", "Tarde", "Plantao"],
    especialidades: ["pos-operatorio", "medicacao", "higiene"],
    descricao:
      "Especialista em cuidados de recuperacao pos-cirurgica com foco em conforto.",
  },
  {
    id: "cg-4",
    nome: "Rita Nascimento",
    idade: 39,
    foto: "https://picsum.photos/seed/caregiver4/600/400",
    cidade: "Sao Paulo",
    bairro: "Aclimacao",
    valorHora: 29,
    experienciaAnos: 4,
    avaliacao: 4.6,
    distanciaKm: 2.1,
    verificado: false,
    disponivel: ["Tarde", "Noite"],
    especialidades: ["companhia", "higiene"],
    descricao:
      "Perfil acolhedor para companhia e apoio em atividades leves da rotina.",
  },
  {
    id: "cg-5",
    nome: "Joao Cesar",
    idade: 45,
    foto: "https://picsum.photos/seed/caregiver5/600/400",
    cidade: "Sao Paulo",
    bairro: "Mooca",
    valorHora: 41,
    experienciaAnos: 10,
    avaliacao: 4.8,
    distanciaKm: 7.8,
    verificado: true,
    disponivel: ["Manha", "Noite"],
    especialidades: ["medicacao", "noturno", "companhia"],
    descricao:
      "Acompanha idosos com comorbidades e possui rotina de checklists de seguranca.",
  },
  {
    id: "cg-6",
    nome: "Vera Santana",
    idade: 52,
    foto: "https://picsum.photos/seed/caregiver6/600/400",
    cidade: "Sao Paulo",
    bairro: "Tatuape",
    valorHora: 36,
    experienciaAnos: 14,
    avaliacao: 4.9,
    distanciaKm: 5.3,
    verificado: true,
    disponivel: ["Plantao", "Noite"],
    especialidades: ["higiene", "mobilidade", "companhia"],
    descricao:
      "Experiencia com idosos acamados e tecnicas de transferencia segura.",
  },
];

export const MOCK_INTERVIEWS: Interview[] = [
  {
    id: "iv-1",
    caregiverId: "cg-1",
    caregiverNome: "Patricia Lima",
    dataISO: "2026-02-20T10:00:00-03:00",
    status: "Confirmada",
    canal: "Video",
  },
  {
    id: "iv-2",
    caregiverId: "cg-3",
    caregiverNome: "Eliane Sousa",
    dataISO: "2026-02-21T16:00:00-03:00",
    status: "Pendente",
    canal: "Presencial",
  },
  {
    id: "iv-3",
    caregiverId: "cg-5",
    caregiverNome: "Joao Cesar",
    dataISO: "2026-02-22T19:00:00-03:00",
    status: "Reagendar",
    canal: "Video",
  },
];

export const MOCK_DAILY_LOGS: DailyCareLog[] = [
  { dia: "Seg", horasCuidado: 4, avaliacaoDia: 4.2, pontualidade: 100 },
  { dia: "Ter", horasCuidado: 6, avaliacaoDia: 4.7, pontualidade: 100 },
  { dia: "Qua", horasCuidado: 5, avaliacaoDia: 4.5, pontualidade: 90 },
  { dia: "Qui", horasCuidado: 8, avaliacaoDia: 4.8, pontualidade: 100 },
  { dia: "Sex", horasCuidado: 7, avaliacaoDia: 4.6, pontualidade: 95 },
  { dia: "Sab", horasCuidado: 3, avaliacaoDia: 4.4, pontualidade: 100 },
  { dia: "Dom", horasCuidado: 2, avaliacaoDia: 4.3, pontualidade: 100 },
];

export const MOCK_MESSAGES: ChatMessage[] = [
  {
    id: "m1",
    autor: "familia",
    texto: "Ola, Patricia. Voce tem experiencia com rotina de medicacao?",
    timestamp: "09:11",
  },
  {
    id: "m2",
    autor: "cuidador",
    texto: "Bom dia! Sim, trabalho com organizacao por horarios e checklist diario.",
    timestamp: "09:14",
  },
  {
    id: "m3",
    autor: "familia",
    texto: "Perfeito. Podemos marcar entrevista na sexta?",
    timestamp: "09:15",
  },
];
